version: '2.0'

services:
  php7:
      build: ./php7
      container_name: php7
      ports:
            - "80:80"
      volumes:
        - ./html:/var/html
      depends_on:
        - mariadb

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_DATABASE: "test_database"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "db1234"
    volumes:
      - ./database/test_database.sql:/docker-entrypoint-initdb.d/test_database.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "81:80"
    depends_on:
      - mariadb
    links:
      - mariadb:db
